
import { Evento } from './types';

export const timelineData: Evento[] = [
  // --- Scritture Ebraiche ---
  { id: 'b-gen', data: '1513', era: 'a.E.V.', anno: 1513, avvenimento: 'Stesura di Genesi', tipo: 'libro', autore: 'Mosè' },
  { id: 'b-exo', data: '1512', era: 'a.E.V.', anno: 1512, avvenimento: 'Stesura di Esodo', tipo: 'libro', autore: 'Mosè' },
  { id: 'b-lev', data: '1512', era: 'a.E.V.', anno: 1512, avvenimento: 'Stesura di Levitico', tipo: 'libro', autore: 'Mosè' },
  { id: 'b-num', data: '1473', era: 'a.E.V.', anno: 1473, avvenimento: 'Stesura di Numeri', tipo: 'libro', autore: 'Mosè' },
  { id: 'b-deu', data: '1473', era: 'a.E.V.', anno: 1473, avvenimento: 'Stesura di Deuteronomio', tipo: 'libro', autore: 'Mosè' },
  { id: 'b-job', data: '1473', era: 'a.E.V.', anno: 1473, avvenimento: 'Stesura di Giobbe', tipo: 'libro', autore: 'Mosè' },
  { id: 'b-jos', data: '1450', era: 'a.E.V.', anno: 1450, avvenimento: 'Stesura di Giosuè', tipo: 'libro', autore: 'Giosuè' },
  { id: 'b-jud', data: '1100', era: 'a.E.V.', anno: 1100, avvenimento: 'Stesura di Giudici', tipo: 'libro', autore: 'Samuele' },
  { id: 'b-rut', data: '1090', era: 'a.E.V.', anno: 1090, avvenimento: 'Stesura di Rut', tipo: 'libro', autore: 'Samuele' },
  { id: 'b-1sa', data: '1078', era: 'a.E.V.', anno: 1078, avvenimento: 'Stesura di 1 Samuele', tipo: 'libro', autore: 'Samuele, Gad, Natan' },
  { id: 'b-2sa', data: '1040', era: 'a.E.V.', anno: 1040, avvenimento: 'Stesura di 2 Samuele', tipo: 'libro', autore: 'Gad, Natan' },
  { id: 'b-son', data: '1020', era: 'a.E.V.', anno: 1020, avvenimento: 'Stesura del Cantico dei Cantici', tipo: 'libro', autore: 'Salomone' },
  { id: 'b-ecc', data: '1000', era: 'a.E.V.', anno: 1000, avvenimento: 'Stesura di Ecclesiaste', tipo: 'libro', autore: 'Salomone' },
  { id: 'b-jon', data: '844', era: 'a.E.V.', anno: 844, avvenimento: 'Stesura di Giona', tipo: 'libro', autore: 'Giona' },
  { id: 'b-joe', data: '820', era: 'a.E.V.', anno: 820, avvenimento: 'Stesura di Gioele', tipo: 'libro', autore: 'Gioele' },
  { id: 'b-amo', data: '804', era: 'a.E.V.', anno: 804, avvenimento: 'Stesura di Amos', tipo: 'libro', autore: 'Amos' },
  { id: 'b-hos', data: '745', era: 'a.E.V.', anno: 745, avvenimento: 'Stesura di Osea', tipo: 'libro', autore: 'Osea' },
  { id: 'b-isa', data: '732', era: 'a.E.V.', anno: 732, avvenimento: 'Stesura di Isaia', tipo: 'libro', autore: 'Isaia' },
  { id: 'b-mic', data: '717', era: 'a.E.V.', anno: 717, avvenimento: 'Stesura di Michea', tipo: 'libro', autore: 'Michea' },
  { id: 'b-pro', data: '717', era: 'a.E.V.', anno: 717, avvenimento: 'Stesura di Proverbi', tipo: 'libro', autore: 'Salomone, Agur, Lemuel' },
  { id: 'b-zeph', data: '648', era: 'a.E.V.', anno: 648, avvenimento: 'Stesura di Sofonia', tipo: 'libro', autore: 'Sofonia' },
  { id: 'b-nah', data: '632', era: 'a.E.V.', anno: 632, avvenimento: 'Stesura di Naum', tipo: 'libro', autore: 'Naum' },
  { id: 'b-hab', data: '628', era: 'a.E.V.', anno: 628, avvenimento: 'Stesura di Abacuc', tipo: 'libro', autore: 'Abacuc' },
  { id: 'b-obad', data: '607', era: 'a.E.V.', anno: 607, avvenimento: 'Stesura di Abdia', tipo: 'libro', autore: 'Abdia' },
  { id: 'b-lam', data: '607', era: 'a.E.V.', anno: 607, avvenimento: 'Stesura di Lamentazioni', tipo: 'libro', autore: 'Geremia' },
  { id: 'b-eze', data: '591', era: 'a.E.V.', anno: 591, avvenimento: 'Stesura di Ezechiele', tipo: 'libro', autore: 'Ezechiele' },
  { id: 'b-1ki', data: '580', era: 'a.E.V.', anno: 580, avvenimento: 'Stesura di 1 e 2 Re', tipo: 'libro', autore: 'Geremia' },
  { id: 'b-dan', data: '536', era: 'a.E.V.', anno: 536, avvenimento: 'Stesura di Daniele', tipo: 'libro', autore: 'Daniele' },
  { id: 'b-hag', data: '520', era: 'a.E.V.', anno: 520, avvenimento: 'Stesura di Aggeo', tipo: 'libro', autore: 'Aggeo' },
  { id: 'b-zec', data: '518', era: 'a.E.V.', anno: 518, avvenimento: 'Stesura di Zaccaria', tipo: 'libro', autore: 'Zaccaria' },
  { id: 'b-est', data: '475', era: 'a.E.V.', anno: 475, avvenimento: 'Stesura di Ester', tipo: 'libro', autore: 'Mardocheo' },
  { id: 'b-ezr', data: '460', era: 'a.E.V.', anno: 460, avvenimento: 'Stesura di Esdra', tipo: 'libro', autore: 'Esdra' },
  { id: 'b-1ch', data: '460', era: 'a.E.V.', anno: 460, avvenimento: 'Stesura di 1 e 2 Cronache', tipo: 'libro', autore: 'Esdra' },
  { id: 'b-psa', data: '460', era: 'a.E.V.', anno: 460, avvenimento: 'Stesura di Salmi', tipo: 'libro', autore: 'Davide, Mosè, figli di Core, ecc.' },
  { id: 'b-neh', data: '443', era: 'a.E.V.', anno: 443, avvenimento: 'Stesura di Neemia', tipo: 'libro', autore: 'Neemia' },
  { id: 'b-mal', data: '443', era: 'a.E.V.', anno: 443, avvenimento: 'Stesura di Malachia', tipo: 'libro', autore: 'Malachia' },

  // --- Scritture Greche ---
  { id: 'b-mat', data: '41', era: 'E.V.', anno: 41, avvenimento: 'Vangelo di Matteo', tipo: 'libro', autore: 'Matteo' },
  { id: 'b-1th', data: '50', era: 'E.V.', anno: 50, avvenimento: '1 Tessalonicesi', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-2th', data: '51', era: 'E.V.', anno: 51, avvenimento: '2 Tessalonicesi', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-gal', data: '52', era: 'E.V.', anno: 52, avvenimento: 'Galati', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-1co', data: '55', era: 'E.V.', anno: 55, avvenimento: '1 Corinti', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-2co', data: '55', era: 'E.V.', anno: 55, avvenimento: '2 Corinti', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-rom', data: '56', era: 'E.V.', anno: 56, avvenimento: 'Romani', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-luk', data: '58', era: 'E.V.', anno: 58, avvenimento: 'Vangelo di Luca', tipo: 'libro', autore: 'Luca' },
  { id: 'b-eph', data: '60', era: 'E.V.', anno: 60, avvenimento: 'Efesini', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-col', data: '61', era: 'E.V.', anno: 61, avvenimento: 'Colossesi', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-phm', data: '61', era: 'E.V.', anno: 61, avvenimento: 'Filemone', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-phi', data: '61', era: 'E.V.', anno: 61, avvenimento: 'Filippesi', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-heb', data: '61', era: 'E.V.', anno: 61, avvenimento: 'Ebrei', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-act', data: '61', era: 'E.V.', anno: 61, avvenimento: 'Atti degli Apostoli', tipo: 'libro', autore: 'Luca' },
  { id: 'b-jam', data: '62', era: 'E.V.', anno: 62, avvenimento: 'Giacomo', tipo: 'libro', autore: 'Giacomo (fratello di Gesù)' },
  { id: 'b-1pe', data: '64', era: 'E.V.', anno: 64, avvenimento: '1 Pietro', tipo: 'libro', autore: 'Pietro' },
  { id: 'b-2pe', data: '64', era: 'E.V.', anno: 64, avvenimento: '2 Pietro', tipo: 'libro', autore: 'Pietro' },
  { id: 'b-1ti', data: '64', era: 'E.V.', anno: 64, avvenimento: '1 Timoteo', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-tit', data: '64', era: 'E.V.', anno: 64, avvenimento: 'Tito', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-mar', data: '65', era: 'E.V.', anno: 65, avvenimento: 'Vangelo di Marco', tipo: 'libro', autore: 'Marco' },
  { id: 'b-2ti', data: '65', era: 'E.V.', anno: 65, avvenimento: '2 Timoteo', tipo: 'libro', autore: 'Paolo' },
  { id: 'b-jud-nt', data: '65', era: 'E.V.', anno: 65, avvenimento: 'Giuda', tipo: 'libro', autore: 'Giuda (fratello di Gesù)' },
  { id: 'b-rev', data: '96', era: 'E.V.', anno: 96, avvenimento: 'Rivelazione (Apocalisse)', tipo: 'libro', autore: 'Giovanni' },
  { id: 'b-joh', data: '98', era: 'E.V.', anno: 98, avvenimento: 'Vangelo di Giovanni', tipo: 'libro', autore: 'Giovanni' },
  { id: 'b-1jo', data: '98', era: 'E.V.', anno: 98, avvenimento: '1 Giovanni', tipo: 'libro', autore: 'Giovanni' },
  { id: 'b-2jo', data: '98', era: 'E.V.', anno: 98, avvenimento: '2 Giovanni', tipo: 'libro', autore: 'Giovanni' },
  { id: 'b-3jo', data: '98', era: 'E.V.', anno: 98, avvenimento: '3 Giovanni', tipo: 'libro', autore: 'Giovanni' },

  // --- Eventi Storici ---
  { id: '1', data: '4026', era: 'a.E.V.', anno: 4026, avvenimento: 'Creazione di Adamo' },
  { id: '3', data: '2370', era: 'a.E.V.', anno: 2370, avvenimento: 'Inizio del Diluvio universale' },
  { id: '5', data: '1943', era: 'a.E.V.', anno: 1943, avvenimento: 'Patto Abraamico' },
  { id: '9', data: '1513', era: 'a.E.V.', anno: 1513, avvenimento: 'Esodo dall’Egitto' },
  { id: '13', data: '1070', era: 'a.E.V.', anno: 1070, avvenimento: 'Davide diventa re' },
  { id: '15', data: '1027', era: 'a.E.V.', anno: 1027, avvenimento: 'Completamento del Tempio' },
  { id: '18', data: '607', era: 'a.E.V.', anno: 607, avvenimento: 'Distruzione di Gerusalemme' },
  { id: '20', data: '537', era: 'a.E.V.', anno: 537, avvenimento: 'Rimpatrio degli ebrei' },
  { id: '24', data: '2', era: 'a.E.V.', anno: 2, avvenimento: 'Nascita di Gesù' },
  { id: 'ev2', data: '33', era: 'E.V.', anno: 33, avvenimento: 'Morte e Risurrezione di Gesù' },
  { id: 'ev5', data: '70', era: 'E.V.', anno: 70, avvenimento: 'Distruzione di Gerusalemme (Roma)' }
];
